import React, { useState } from 'react';
import { useStore } from '../context/StoreContext';
import { ProductCategory, Product } from '../types';
import { Trash, Plus, Image as ImageIcon, AlertCircle } from 'lucide-react';
import { Navigate } from 'react-router-dom';

const Admin: React.FC = () => {
  const { user, products, orders, addProduct, deleteProduct } = useStore();
  const [activeTab, setActiveTab] = useState<'products' | 'orders'>('products');
  const [isSubmitting, setIsSubmitting] = useState(false);
  
  // Form State
  const [newProduct, setNewProduct] = useState<Partial<Product>>({
    name: '',
    price: 0,
    category: ProductCategory.RINGS,
    description: '',
    stock: 0,
    image: ''
  });

  if (!user) {
    return <Navigate to="/auth" />;
  }

  const handleAddProduct = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newProduct.name || !newProduct.price) return;
    
    setIsSubmitting(true);

    await addProduct({
      ...newProduct,
      // ID is generated by DB
      id: '', 
      image: newProduct.image || 'https://picsum.photos/seed/default/800/800'
    } as Product);
    
    setIsSubmitting(false);
    setNewProduct({
        name: '',
        price: 0,
        category: ProductCategory.RINGS,
        description: '',
        stock: 0,
        image: ''
    });
    alert("Product added!");
  };

  const handleDelete = async (id: string) => {
    if(window.confirm("Are you sure you want to delete this product?")) {
      await deleteProduct(id);
    }
  };

  return (
    <div className="max-w-7xl mx-auto px-6 py-12">
      <div className="flex justify-between items-center mb-8">
        <h1 className="text-3xl font-serif">Admin Dashboard</h1>
        <div className="space-x-4">
          <button 
            onClick={() => setActiveTab('products')} 
            className={`px-4 py-2 text-sm ${activeTab === 'products' ? 'bg-black text-white' : 'bg-gray-100'}`}
          >
            Products
          </button>
          <button 
            onClick={() => setActiveTab('orders')} 
            className={`px-4 py-2 text-sm ${activeTab === 'orders' ? 'bg-black text-white' : 'bg-gray-100'}`}
          >
            Orders
          </button>
        </div>
      </div>

      {activeTab === 'products' ? (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Add Product Form */}
          <div className="bg-gray-50 p-6 h-fit sticky top-24">
            <h3 className="font-medium mb-4 flex items-center gap-2"><Plus size={16}/> Add New Product</h3>
            <form onSubmit={handleAddProduct} className="space-y-4">
              <input 
                className="w-full border p-2 text-sm focus:border-black outline-none" 
                placeholder="Product Name" 
                value={newProduct.name}
                onChange={e => setNewProduct({...newProduct, name: e.target.value})}
              />
              
              <div className="flex gap-2">
                <input 
                  type="number" 
                  className="w-1/2 border p-2 text-sm focus:border-black outline-none" 
                  placeholder="Price" 
                  value={newProduct.price || ''}
                  onChange={e => setNewProduct({...newProduct, price: Number(e.target.value)})}
                />
                <select 
                  className="w-1/2 border p-2 text-sm focus:border-black outline-none"
                  value={newProduct.category}
                  onChange={e => setNewProduct({...newProduct, category: e.target.value as ProductCategory})}
                >
                  {Object.values(ProductCategory).map(c => <option key={c} value={c}>{c}</option>)}
                </select>
              </div>

              <div>
                <label className="block text-xs text-gray-500 mb-1">Image URL</label>
                <input 
                  className="w-full border p-2 text-sm focus:border-black outline-none" 
                  placeholder="https://..." 
                  value={newProduct.image}
                  onChange={e => setNewProduct({...newProduct, image: e.target.value})}
                />
                <p className="text-[10px] text-gray-400 mt-1">
                   Paste a direct link to an image hosted on Imgur, AWS, etc.
                </p>
              </div>

              {/* Image Preview */}
              {newProduct.image && (
                <div className="aspect-square w-full bg-white border border-gray-200 flex items-center justify-center overflow-hidden">
                  <img 
                    src={newProduct.image} 
                    alt="Preview" 
                    className="w-full h-full object-cover"
                    onError={(e) => {
                      (e.target as HTMLImageElement).style.display = 'none';
                      (e.target as HTMLImageElement).parentElement!.innerHTML = '<span class="text-xs text-red-500 flex flex-col items-center"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="12"></line><line x1="12" y1="16" x2="12.01" y2="16"></line></svg>Invalid Image URL</span>';
                    }}
                  />
                </div>
              )}

              <textarea 
                className="w-full border p-2 text-sm focus:border-black outline-none" 
                placeholder="Description" 
                rows={3}
                value={newProduct.description}
                onChange={e => setNewProduct({...newProduct, description: e.target.value})}
              />
              <button 
                disabled={isSubmitting}
                className="w-full bg-black text-white py-3 text-sm hover:bg-gray-800 transition-colors uppercase tracking-wide disabled:opacity-50"
              >
                {isSubmitting ? 'Adding...' : 'Add Product'}
              </button>
            </form>
          </div>

          {/* Product List */}
          <div className="lg:col-span-2">
             <table className="w-full text-sm text-left">
               <thead className="bg-gray-100 text-gray-600 uppercase">
                 <tr>
                   <th className="p-3">Image</th>
                   <th className="p-3">Name</th>
                   <th className="p-3">Price</th>
                   <th className="p-3">Actions</th>
                 </tr>
               </thead>
               <tbody>
                 {products.map(p => (
                   <tr key={p.id} className="border-b border-gray-100 hover:bg-gray-50">
                     <td className="p-3">
                       <div className="w-12 h-12 bg-gray-100 overflow-hidden">
                         <img src={p.image} className="w-full h-full object-cover" alt="" />
                       </div>
                     </td>
                     <td className="p-3 font-medium">{p.name}</td>
                     <td className="p-3">${p.price}</td>
                     <td className="p-3">
                       <button onClick={() => handleDelete(p.id)} className="text-red-500 hover:text-red-700 transition-colors">
                         <Trash size={16} />
                       </button>
                     </td>
                   </tr>
                 ))}
               </tbody>
             </table>
          </div>
        </div>
      ) : (
        /* Orders List */
        <div className="bg-white border border-gray-100">
          {orders.length === 0 ? (
            <div className="p-8 text-center text-gray-500">No orders placed yet.</div>
          ) : (
             <table className="w-full text-sm text-left">
               <thead className="bg-gray-100 text-gray-600 uppercase">
                 <tr>
                   <th className="p-4">Order ID</th>
                   <th className="p-4">Date</th>
                   <th className="p-4">Total</th>
                   <th className="p-4">Status</th>
                 </tr>
               </thead>
               <tbody>
                 {orders.map(o => (
                   <tr key={o.id} className="border-b border-gray-100">
                     <td className="p-4 font-mono text-gray-500">#{o.id}</td>
                     <td className="p-4">{new Date(o.date).toLocaleDateString()}</td>
                     <td className="p-4 font-medium">${o.total.toFixed(2)}</td>
                     <td className="p-4">
                       <span className="bg-yellow-100 text-yellow-800 px-2 py-1 rounded-full text-xs font-medium">
                         {o.status}
                       </span>
                     </td>
                   </tr>
                 ))}
               </tbody>
             </table>
          )}
        </div>
      )}
    </div>
  );
};

export default Admin;